### ISSUE TITLE
ValueError：array  must not contain infs or NaNs.

### ISSUE THREAD

**Issue by enjoy-our-life** [Deep-MI/BrainPrint-python#4]
Hi，
Recently,I use  Brainprint  to process my data.Some outputs of Brainprint have problems.There is no csv file in the eigenvectors folder.The result is that brainprint.csv and brainprint.asymmetry.csv are missing from the output.Please let me know how to resolve such issue?
ValueError：array  must not contain infs or NaNs.

**Comment by kdiers** [comment]
Hello,

thanks for your report. Kindly let me know which command / options you are using, and which FreeSurfer version. 

If you can share one example case where the processing fails, it would be very helpful to replicate the issue - I can send an upload link.

Best regards, Kersten

**Comment by kdiers** [comment]
Hi, thanks for the upload. 

I found for both cases some issues with the cortical surface. The construction of this surface can be a bit error-prone, so if the cortex is not your primary interest, then you can always use the `--skipcortex` option to leave out these structures. The script should run through successfully when using this option. 

If you prefer to analyze the cortical surfaces:

- One issue was related to surface elements (triangles) being oriented in part clockwise, in part counter-clockwise. This does not affect surface properties such as area, volume, or thickness, but could impact some computations within the brainprint/shapeDNA script, which would cause the script to fail, i.e. produce an error message. This has been fixed so that surfaces are oriented consistently now. 
- The other issue was related to surface normalization, which required computation of the surface area. This could not be computed for one specific cortical surface; I speculate due to a problem with mesh quality such as degenerate surface elements. I can't tell the exact reason, but have "fixed" the script in such a way that for this particular structure a warning message is produced and the output will contain a NaN (not a number value) instead of e.g. a numerical asymmetry value for this particular structure. That is, the script should run through even in cases with potential mesh quality issues, and produce NaN output in such a situation.

Hope this helps, Kersten

**Comment by enjoy-our-life** [comment]
Thank you for your help，Kersten.
